spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hexagonal_db
    username: postgres
    password: 
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect